/** Declaration file generated by dts-gen */
interface Options {
  limit?: number;
  offset?: number;
  authentication?: { username?: string; password?: string };
  search?: unknown;
  set?: unknown;
}

declare class stein_js_client {
  constructor(storageURL: any);

  append(sheetName: string, rows?: unknown, { authentication }?: Options): any;

  delete(sheetName: string, { search, limit, authentication }?: Options): any;

  edit(
    sheetName: string,
    { search, set, limit, authentication }?: Options
  ): any;

  read<T>(
    sheetName: string,
    { limit, offset, search, authentication }?: Options
  ): Promise<T>;
}

declare module 'stein-js-client' {
  export = stein_js_client;
}
